services:

    article-magick-web:

        container_name: article-magick-web
        
        image: softwareshinobi/article-magick-web

        build: 

            context: .

            dockerfile: Dockerfile

        restart: always

        ports:

            - "80:80"
